In [ ]:
def factorial(n):
    fact=1
    for i in range(2,n+1):
        fact*=i
    return fact

num=int(input("Enter the number "))
print(factorial(num))

In [ ]:
def CTF(temp):
    temp=(((9/5)*temp)+32)
    return temp
temp=int(input("ENter the temp in cel "))
print(CTF(temp))


In [ ]:
def fn(a,b,c=10,d=5):
    s=a/b+c/d
    return s,a,b,c,d
fn(b=2,a=4,c=10,d=100)

In [ ]:
import time
print("Welcome shri narendra damodardas modi")
time.sleep(1)
print("Welcome selmon bhoi")
time.sleep(1)
print("welcome thugadeepa darshan ")

In [ ]:
lst=[i for i in range(100) if i%2==0]
print(lst)

In [ ]:
import numpy as np
a=[[1,2,3,4],[5,6,7,8],[1,2,3,4]]
n1=np.array(a)
b=np.reshape(n1,(4,3))
print(b)

In [ ]:
nr=np.random.randint((4,4))
print(nr)

In [ ]:
a=[1,2,3,4]
n1=np.array(a,dtype="str")
print(n1)
n1.dtype
type(n1)

In [8]:
import numpy as np
a=[1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5]
print("mean is :",np.mean(a))
print("median is :",np.median(a))


mean is : 3.0
median is : 3.0


In [1]:
import numpy as np 

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
 np.ones((9,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [6]:
 d = np.arange(10,25,5) 
d

array([10, 15, 20])

In [12]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
A=np.array([10,20,30])

In [18]:
B=np.array([40,50,60])

#### Add 2 arrays

In [19]:
C=A+B
C

array([50, 70, 90])

#### Multiply 2 arrays

In [20]:
C=A*B
C

array([ 400, 1000, 1800])

In [22]:
np.mean(A)



50.0

In [23]:
np.mean(B)


50.0

In [26]:
import math
math.sqrt(np.std(A))

2.8574404296987996

In [27]:
math.sqrt(np.std(B))

2.8574404296987996